language: python
python: '2.7'
sudo: false
branches:
  only:
  - master
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
addons:
  firefox: '42.0'
install:
- pip install -r requirements/tox.txt
script:
- tox -e py27
- tox -e doc
after_success:
- pip install coveralls
- coveralls
