language: python
python:
 - '2.7'
 - '3.5'
 - '3.6'
sudo: false
branches:
  only:
  - master
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3 # give xvfb some time to start
- wget https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.20.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
addons:
  firefox: '59.0.1'
install:
- pip install -r requirements/travis.txt
script:
- tox -- -n 2 --durations=10
- tox -e doc
after_success:
- codecov
deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
  password:
    secure: o6earhHeqUFjY2d9Xrn3w2KpQ9ej96S+BnL0Us8XiTQtvgvhdkAKdH0xIxBWwQiWYT6ZyN8XzDQrvPTM6jnhEuGkY2Qv7GVnPXNu2YimvUm9gkmMtzphII/KSNnqrAMPzHL1ICUKe73fLFxi9ipBWcfN2UDi3Lw1BG78zTmmaGc=
