language: python
python:
 - '2.7'
 - '3.5'
 - 'pypy'
sudo: false
branches:
  only:
  - master
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
addons:
  firefox: '42.0'
install:
- pip install -r requirements/tox.txt
- pip install tox-travis
script:
- tox -- --durations=10
- tox -e doc
after_success:
- pip install coveralls
- coveralls
